# Generated by Django 5.2.7 on 2025-10-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("brand", models.CharField(blank=True, max_length=120)),
                (
                    "serving_size",
                    models.DecimalField(
                        decimal_places=2, help_text="Default serving size", max_digits=6
                    ),
                ),
                ("serving_unit", models.CharField(default="g", max_length=32)),
                ("calories", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "carbs_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
                "ordering": ["name"],
            },
        ),
    ]
