# Generated by Django 5.2.7 on 2025-10-07 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Health Condition",
                "verbose_name_plural": "Health Conditions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("SED", "Sedentary (office job)"),
                            ("LGT", "Lightly active"),
                            ("MOD", "Moderately active"),
                            ("ACT", "Very active"),
                            ("ATH", "Athlete"),
                        ],
                        default="SED",
                        max_length=3,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("LOSE", "Fat loss"),
                            ("MAINTAIN", "Maintain weight"),
                            ("GAIN", "Gain muscle/weight"),
                        ],
                        default="MAINTAIN",
                        max_length=8,
                    ),
                ),
                ("dietary_preferences", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "health_conditions",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="users.healthcondition"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
