version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["deps"]
    # reviewers: ["your-org/real-team"]
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["deps"]
    # reviewers: ["your-org/real-team"]
