# Generated by Django 5.2.7 on 2025-10-07 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Plan",
                "verbose_name_plural": "Weekly Plans",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (5, "شنبه"),
                            (6, "یک‌شنبه"),
                            (0, "دوشنبه"),
                            (1, "سه‌شنبه"),
                            (2, "چهارشنبه"),
                            (3, "پنج‌شنبه"),
                            (4, "جمعه"),
                        ]
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "صبحانه"),
                            ("lunch", "ناهار"),
                            ("dinner", "شام"),
                            ("snack", "میان‌وعده"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "servings",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foods.food"
                    ),
                ),
                (
                    "weekly_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="plans.weeklyplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Item",
                "verbose_name_plural": "Plan Items",
                "ordering": ["day_of_week", "meal_type"],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklyplan",
            constraint=models.UniqueConstraint(
                fields=("user", "start_date"), name="unique_weekly_plan_per_user_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.UniqueConstraint(
                fields=("weekly_plan", "day_of_week", "meal_type"),
                name="unique_plan_item_per_day_meal",
            ),
        ),
    ]
