blank_issues_enabled: false
contact_links:
  - name: سوالات عمومی
    url: https://github.com/mehran-shabani/Nutrition/discussions
    about: برای سوالات غیرمرتبط با باگ یا feature جدید از Discussions استفاده کنید و حتماً OWNER/REPO را با نام مخزن خود جایگزین کنید.
